services:
  app:
    build: .
    container_name: flask_app
    expose:
      - "5000"
    volumes:
      - db-data:/app/instance
    networks:
      - onion_net

  tor:
    image: osminogin/tor-simple:latest
    container_name: tor_service
    volumes:
      - ./tor/torrc:/etc/tor/torrc
    networks:
      - onion_net
    depends_on:
      - app

volumes:
  db-data:

networks:
  onion_net:
    driver: bridge